### ISSUE TITLE
starting at any gene

### ISSUE THREAD

**Issue by jflot** [odethier-ulb/mtSVG#1]
Hi Olivier,
Instead of `--cox2cob <boolean>`, it would be great to have an option `--start <gene name>` so that users could start their ribbon at the beginning of any gene they like (typical options in the groups I work on are to start the ribbons at the beginning of cox1 or trnM).

**Comment by odethier-ulb** [comment]
Hello jflot,

The argument `--cox2cob` has been removed and replaced with `--start <gene name>` as requested and the default gene name is cox1. A new argument `--reverse true/false` has also been added if the user want to reverse the gene order in the gff.
