### ISSUE TITLE
add option for linear mitochondrial genomes

### ISSUE THREAD

**Issue by jflot** [odethier-ulb/mtSVG#8]
In case of linear mitochondrial genomes (which is the case for Medusozoa, various protists, some yeasts,...), the ribbon should not be rotated to start at cox1 but rather the original, linear gene order of the GFA should be displayed. Maybe a --linear option would be the best way to indicate this?

**Comment by odethier-ulb** [comment]
I can add a `--linear` option that will do the same as `--start <first gene listed in the gff>`, is it what you want?

**Comment by jflot** [comment]
Yes, this would be perfect.

**Comment by odethier-ulb** [comment]
Done
